data_paths:
  clean_data: 'data/raw/carseg_data/clean_data'
  test_set_filenames: 'references/test_set_ids.txt'

model_paths:
  unet_scale_05: 'models/unet_carvana_scale0.5_epoch2.pth'

hyperparameters:
  batch_size: 16
  learning_rate: 1e-3
  weight_decay: 1E-3
  num_epochs: 5
  validation_every_steps: 500

unet_parameters:
  nb_output_channels: 9
  to_finetune: ['outc']