cuda: 0
name: 'v1'

log_wandb: True

# For Predictions
name_best: 'v0'
predict_dataset: 'valid'

data_paths:
  clean_data: 'data/raw/carseg_data/clean_data'
  test_set_filenames: 'references/test_set_ids.txt'

model_paths:
  models: 'models/'

hyperparameters:
  batch_size: 24 # max 24 anything more cuda runs out of memory
  num_workers: 24
  learning_rate: 0.25
  weight_decay: 1E-3
  num_epochs: 100
  validation_every_steps: 100 #500
  T_max: 100

autoencoder_parameters:
  nb_output_channels: 9
  nb_input_channels: 3