cuda: 0
name: 'v6'

log_wandb: True

# For Predictions
name_best: 'v6'
predict_dataset: 'valid'

data_paths:
  clean_data: 'data/raw/carseg_data/clean_data'
  test_set_filenames: 'references/test_set_ids.txt'

model_paths:
  models: 'models/'
  unet_scale_05: 'models/unet_carvana_scale0.5_epoch2.pth'

hyperparameters:
  batch_size: 32
  num_workers: 32
  learning_rate: 1e-3
  weight_decay: 1E-3
  num_epochs: 100
  validation_every_steps: 100 #500
  T_max: 100

unet_parameters:
  nb_output_channels: 9
  to_finetune: 'all'  #['outc']