cuda: 0
name: 'v1'

log_wandb: True

# For Predictions
name_best: 'v1'
predict_dataset: 'test'

data_paths:
  clean_data: 'data/raw/carseg_data/clean_data'
  test_set_filenames: 'references/test_set_ids.txt'

model_paths:
  models: 'models/'
  unet_scale_05: 'models/unet_carvana_scale0.5_epoch2.pth'

hyperparameters:
  batch_size: 16
  num_workers: 16
  learning_rate: 1e-3
  weight_decay: 1E-3
  num_epochs: 100
  validation_every_steps: 100 #500

unet_parameters:
  nb_output_channels: 9
  to_finetune: ['outc'] #'all' 